### PR TITLE
Documentation for working with clock (circadian) model

### PR DESCRIPTION
**Pull request by csnazell**
Drafted description of clock model and how to create a new clock model from scratch.

Outstanding:
- [x] - need to verify code examples work as per expectation.

### CODE REVIEW

**Comment by csnazell** [comment]
Addresses Issue #1

**Comment by csnazell** [comment]
Tried out new clock example, identified areas where it didn't work & updated the docs accordingly.

**Review by ReaAntKour — COMMENTED** [review]
I added citation to Battle et al 2024 for the F2014.COP1 and made other small edits.

Further suggestions:

Explain what “sunset” and ConstantModel mean and what is needed to define the environment. A simple user for the code will likely not want to change the model, but they will need to change the environment. A more advanced user will also want to change the model and they will have more knowledge and will be able to get the information they need with the help of this documentation. 

Would be nice for parameters to say which “sets” are available (which possible genotype values are predefined).

For the “Using a Clock Model” section where you explain entrainment, it might help to add some more explanation (possibly in the code itself) for what is being changed by the entrain function. I was looking at the example trying to figure this out and I had to look at the code and still struggled. But as I say, this might be more appropriate locally in the function code rather than the docs. What do you think?

Great that there are instructions for Creating Your Model!
You say that it is good to review one of the existing implementations. There are a few different files called Clock or in the Clock folder. Is there a specific one that would be the right guide? Can you give a specific example? You could say something like “(e.g. plant-model/PlantModelFramework/src/Clocks/F2014.jl)”, if that is the right example.
In Dependencies, your clock model does not have “using PlantModelFramework”, right? Why is that not necessary in that case but necessary for the Experimental Clock?

I changed ExperimentClock.jl to ExperimentalClock.jl as I assumed it was a typo. Please correct if this was different on purpose.

Is midnight really the middle of the night or is it the 24h timepoint? If lights come on at 24h (aka at 0h), then this is not midnight. I couldn’t figure out for the statesAtMidnight when this actually is. And I wasn’t sure when lights come on.

Why are there negative values in the 41-element Vector? What does this represent? They are also all the same.

**Comment by csnazell** [comment]
> Explain what “sunset” and ConstantModel mean and what is needed to define the environment. ...

I've created issue #6 to cover documentation of environment model & included task to update this document (linking &c) when the environment model docs exist.

**Comment by csnazell** [comment]
> Would be nice for parameters to say which “sets” are available (which possible genotype values are predefined).

I'll add an additional doc covering implemented models. I think this are the red * blue variants for the F2014 COP1 model.

**Comment by csnazell** [comment]
> For the “Using a Clock Model” section where you explain entrainment, ...

I think adding some expansion of what's going on with entrainment probably needs to be in both locations. Probably a quick note in the docs and a few lines in the code. From a purely functional point of view this step essentially produces the initial conditions for clock model simulation run. I think it's necessary to give the clock model a chance to align with the environmental inputs to the model. 

The Framework V2 Model paper doesn't really touch on what's happening but it does reference a couple of papers:

Locke JC, Southern MM, Kozma-Bognar L, Hibberd V, Brown PE, Turner MS, Millar AJ. 2005. Extension of a genetic network model by iterative experimentation and mathematical analysis. Molecular Systems Biology 1:2005–0013.

Haydon MJ, Mielczarek O, Robertson FC, Hubbard KE, Webb AA. 2013. Photosynthetic entrainment of the Arabidopsis thaliana cir- cadian clock. Nature 502:689–692.

**Comment by csnazell** [comment]
> You say that it is good to review one of the existing implementations. ... 

I 'll add some detail on where the clock elements of the framework are within the package with some info on the structure and how they work with one another.

I'll add a call out the F2014.jl source.

**Comment by csnazell** [comment]
> In Dependencies, your clock model does not have “using PlantModelFramework”, right? Why is that not necessary in that case but necessary for the Experimental Clock?

My intention was that step "\#2 Create The Boilerplate" is literally just a blank first step with the comments indicating the overall structure. Each subsequent step fills in the blanks. I'll add the comment lines into these steps to make it clearer.

**Comment by csnazell** [comment]
> Is midnight really the middle of the night or is it the 24h timepoint? ... 

It's just the 24h / 0h timepoint. I'll change the wording to clarify matters. With the sunset set to 8 the daylight period is effectively 0h through to 8h for an 8 hour photoperiod.

**Comment by csnazell** [comment]
> Why are there negative values in the 41-element Vector? What does this represent? They are also all the same. 

These are the caluclated outcomes of the differential equations as written. I just made the DEs up as simple example boilerplate. SciML complains they're not stable but it does run.

I'll add some text highlighting that the DEs are merely illustrative and don't represent anything in particular.

**Review by ReaAntKour — APPROVED** [review]
Looks great!

**Pull request merged**
